// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sport_shop_ver2.Models;

#nullable disable

namespace sport_shop_ver2.Migrations
{
    [DbContext(typeof(SportShopContext))]
    partial class SportShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("sport_shop_ver2.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.HasKey("Id")
                        .HasName("categories_pkey");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("sport_shop_ver2.Models.DeleveryPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeliveryAdress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delivery_adress");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("delevery_points_pkey");

                    b.ToTable("delevery_points", (string)null);
                });

            modelBuilder.Entity("sport_shop_ver2.Models.HistoryOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<int>("IdDeliveryPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_delivery_point");

                    b.Property<int>("IdStatuses")
                        .HasColumnType("integer")
                        .HasColumnName("id_statuses");

                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.HasKey("Id")
                        .HasName("history_orders_pkey");

                    b.HasIndex("IdDeliveryPoint");

                    b.HasIndex("IdStatuses");

                    b.HasIndex("IdUser");

                    b.ToTable("history_orders", (string)null);
                });

            modelBuilder.Entity("sport_shop_ver2.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manufacturer_name");

                    b.HasKey("Id")
                        .HasName("manufacturers_pkey");

                    b.ToTable("manufacturers", (string)null);
                });

            modelBuilder.Entity("sport_shop_ver2.Models.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MeasureName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("measure_name");

                    b.HasKey("Id")
                        .HasName("measures_pkey");

                    b.ToTable("measures", (string)null);
                });

            modelBuilder.Entity("sport_shop_ver2.Models.Role", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("sport_shop_ver2.Models.SportingProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Art")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("art");

                    b.Property<int>("CointInStok")
                        .HasColumnType("integer")
                        .HasColumnName("coint_in_stok");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Discount")
                        .HasColumnType("integer")
                        .HasColumnName("discount");

                    b.Property<int>("IdCategory")
                        .HasColumnType("integer")
                        .HasColumnName("id_category");

                    b.Property<int>("IdManufacturer")
                        .HasColumnType("integer")
                        .HasColumnName("id_manufacturer");

                    b.Property<int>("IdMeasure")
                        .HasColumnType("integer")
                        .HasColumnName("id_measure");

                    b.Property<int>("IdSupplier")
                        .HasColumnType("integer")
                        .HasColumnName("id_supplier");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.HasKey("Id")
                        .HasName("sporting_products_pkey");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdManufacturer");

                    b.HasIndex("IdMeasure");

                    b.HasIndex("IdSupplier");

                    b.ToTable("sporting_products", (string)null);
                });

            modelBuilder.Entity("sport_shop_ver2.Models.SportingProductsHistoryOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<int>("IdOrder")
                        .HasColumnType("integer")
                        .HasColumnName("id_order");

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer")
                        .HasColumnName("id_product");

                    b.HasKey("Id")
                        .HasName("sporting_products_history_orders_pkey");

                    b.HasIndex("IdOrder");

                    b.HasIndex("IdProduct");

                    b.ToTable("sporting_products_history_orders", (string)null);
                });

            modelBuilder.Entity("sport_shop_ver2.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_name");

                    b.HasKey("Id")
                        .HasName("statuses_pkey");

                    b.ToTable("statuses", (string)null);
                });

            modelBuilder.Entity("sport_shop_ver2.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier_name");

                    b.HasKey("Id")
                        .HasName("suppliers_pkey");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("sport_shop_ver2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<short>("IdRole")
                        .HasColumnType("smallint")
                        .HasColumnName("id_role");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("IdRole");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("sport_shop_ver2.Models.HistoryOrder", b =>
                {
                    b.HasOne("sport_shop_ver2.Models.DeleveryPoint", "IdDeliveryPointNavigation")
                        .WithMany("HistoryOrders")
                        .HasForeignKey("IdDeliveryPoint")
                        .IsRequired()
                        .HasConstraintName("history_orders_id_delivery_point_fkey");

                    b.HasOne("sport_shop_ver2.Models.Status", "IdStatusesNavigation")
                        .WithMany("HistoryOrders")
                        .HasForeignKey("IdStatuses")
                        .IsRequired()
                        .HasConstraintName("history_orders_id_statuses_fkey");

                    b.HasOne("sport_shop_ver2.Models.User", "IdUserNavigation")
                        .WithMany("HistoryOrders")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("history_orders_id_user_fkey");

                    b.Navigation("IdDeliveryPointNavigation");

                    b.Navigation("IdStatusesNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("sport_shop_ver2.Models.SportingProduct", b =>
                {
                    b.HasOne("sport_shop_ver2.Models.Category", "IdCategoryNavigation")
                        .WithMany("SportingProducts")
                        .HasForeignKey("IdCategory")
                        .IsRequired()
                        .HasConstraintName("sporting_products_d_category_fkey");

                    b.HasOne("sport_shop_ver2.Models.Manufacturer", "IdManufacturerNavigation")
                        .WithMany("SportingProducts")
                        .HasForeignKey("IdManufacturer")
                        .IsRequired()
                        .HasConstraintName("sporting_products_id_manufacturer_fkey");

                    b.HasOne("sport_shop_ver2.Models.Measure", "IdMeasureNavigation")
                        .WithMany("SportingProducts")
                        .HasForeignKey("IdMeasure")
                        .IsRequired()
                        .HasConstraintName("sporting_products_id_measure_fkey");

                    b.HasOne("sport_shop_ver2.Models.Supplier", "IdSupplierNavigation")
                        .WithMany("SportingProducts")
                        .HasForeignKey("IdSupplier")
                        .IsRequired()
                        .HasConstraintName("sporting_products_id_supplier_fkey");

                    b.Navigation("IdCategoryNavigation");

                    b.Navigation("IdManufacturerNavigation");

                    b.Navigation("IdMeasureNavigation");

                    b.Navigation("IdSupplierNavigation");
                });

            modelBuilder.Entity("sport_shop_ver2.Models.SportingProductsHistoryOrder", b =>
                {
                    b.HasOne("sport_shop_ver2.Models.HistoryOrder", "IdOrderNavigation")
                        .WithMany("SportingProductsHistoryOrders")
                        .HasForeignKey("IdOrder")
                        .IsRequired()
                        .HasConstraintName("sporting_products_history_orders_id_order_fkey");

                    b.HasOne("sport_shop_ver2.Models.SportingProduct", "IdProductNavigation")
                        .WithMany("SportingProductsHistoryOrders")
                        .HasForeignKey("IdProduct")
                        .IsRequired()
                        .HasConstraintName("sporting_products_history_orders_id_product_fkey");

                    b.Navigation("IdOrderNavigation");

                    b.Navigation("IdProductNavigation");
                });

            modelBuilder.Entity("sport_shop_ver2.Models.User", b =>
                {
                    b.HasOne("sport_shop_ver2.Models.Role", "IdRoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("users_id_role_fkey");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("sport_shop_ver2.Models.Category", b =>
                {
                    b.Navigation("SportingProducts");
                });

            modelBuilder.Entity("sport_shop_ver2.Models.DeleveryPoint", b =>
                {
                    b.Navigation("HistoryOrders");
                });

            modelBuilder.Entity("sport_shop_ver2.Models.HistoryOrder", b =>
                {
                    b.Navigation("SportingProductsHistoryOrders");
                });

            modelBuilder.Entity("sport_shop_ver2.Models.Manufacturer", b =>
                {
                    b.Navigation("SportingProducts");
                });

            modelBuilder.Entity("sport_shop_ver2.Models.Measure", b =>
                {
                    b.Navigation("SportingProducts");
                });

            modelBuilder.Entity("sport_shop_ver2.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("sport_shop_ver2.Models.SportingProduct", b =>
                {
                    b.Navigation("SportingProductsHistoryOrders");
                });

            modelBuilder.Entity("sport_shop_ver2.Models.Status", b =>
                {
                    b.Navigation("HistoryOrders");
                });

            modelBuilder.Entity("sport_shop_ver2.Models.Supplier", b =>
                {
                    b.Navigation("SportingProducts");
                });

            modelBuilder.Entity("sport_shop_ver2.Models.User", b =>
                {
                    b.Navigation("HistoryOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
